all: SO2_Projekt

SO2_Projekt: main.cpp
			g++ -std=c++11 -Wall -g main.cpp Car.cpp Crossing.cpp Parking.cpp Human.cpp WalkerCrossing.cpp Tram.cpp TramCrossing.cpp LightResource.cpp StreetLight.cpp -o main -lncurses -pthread
